#add postgres
#name the services
#create custom image for services
#push to dockerhub
#
services:
  metabase:
    build: 
      context: .
      target: ${DOCKER_TARGET}
    image: harun702/metabase
    container_name: metabase-app

    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: user
      MB_DB_HOST: db
    restart: unless-stopped

  # ui:
  #   build:
  #     context: ./docker-lesson
  #     dockerfile: frontend.dockerfile
  #   image: harun702/demo-ui
  #   ports: 
  #     - "4069:80"
  #   restart: always

  # backend:
  #   build:
  #     context: ./docker-lesson
  #     dockerfile: backend.dockerfile
  #   image: harun702/demo-api
  #   ports: 
  #     - "5000:5000"
  #   restart: no
    
  db:
    image: postgres:15
    container_name: metabase-postgres
    environment: 
      POSTGRES_DB: metabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    restart: on-failure




  
  


