services:
  app:
    image: matomo
    container_name: matomo
    ports:
      - "8000:80"
    environment:
      MATOMO_DATABASE_DBNAME: matomo_db
      MATOMO_DATABASE_USERNAME: test
      MATOMO_DATABASE_PASSWORD: test
      MATOMO_DATABASE_HOST: db
    volumes:
      - matomo:/var/www/html  
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: matomo_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    restart: on-failure:10 
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  matomo:
  dbdata:
