services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_DATABASE_TYPE=${GF_DATABASE_TYPE}
      - GF_DATABASE_HOST=${GF_DATABASE_HOST}
      - GF_DATABASE_NAME=${GF_DATABASE_NAME}
      - GF_DATABASE_USER=${GF_DATABASE_USER}
      - GF_DATABASE_PASSWORD=${GF_DATABASE_PASSWORD}
    ports:
     - '3333:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - grafana-db

  grafana-db:
    image: postgres:15
    container_name: grafana-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - grafana-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  grafana-storage:
  grafana-db-data: