services:
  obsidian:
    image: lscr.io/linuxserver/obsidian
    container_name: obsidian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./obsidian-data:/config
    ports:
      - 3421:3000
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  obsidian-data: