services:
  obsidian:
    image: lscr.io/linuxserver/obsidian
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - ./obsidian-data:/config
    ports:
      - 3421:3000
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  obsidian-data: