services:
  app:
    image: matomo
    container_name: matomo
    ports:
      - "8000:80"
    environment:
      MATOMO_DATABASE_DBNAME: matomo_db
      MATOMO_DATABASE_USERNAME: test
      MATOMO_DATABASE_PASSWORD: test
      MATOMO_DATABASE_HOST: matomo_db
    volumes:
      - matomo:/var/www/html
    depends_on: 
      - matomo_db
    restart: always

  matomo_db:
    image: mariadb
    container_name: matomo_mysql
    environment:
      MYSQL_DATABASE: matomo_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - dbdata-matomo:/var/lib/mysql
    restart: always

volumes:
  matomo:
  dbdata-matomo: