services:
  app:
    image: matomo
    container_name: matomo
    ports:
      - "8000:80"
    environment:
      MATOMO_DATABASE_DBNAME: ${MATOMO_DB_NAME}
      MATOMO_DATABASE_USERNAME: ${MATOMO_DB_USER}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DB_PASS}
      MATOMO_DATABASE_HOST: ${MATOMO_DB_HOST}
    volumes:
      - matomo:/var/www/html
    depends_on: 
      - matomo_db
    restart: always

  matomo_db:
    image: mariadb
    container_name: matomo_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    ports:
      - "3306:3306"
    volumes:
      - dbdata-matomo:/var/lib/mysql
    restart: always

volumes:
  matomo:
  dbdata-matomo: